import React, { useState } from 'react';

export default function SOPForm() {
  const [sop, setSop] = useState('');
  const [highlight, setHighlight] = useState('');
  const wordCount = sop.trim().split(/\s+/).filter(Boolean).length;

  return (
    <div className="max-w-7xl mx-auto p-6 bg-white rounded-2xl shadow-md mt-10">
      <div className="flex flex-col lg:flex-row gap-10">
        {/* Main Content */}
        <div className="flex-1 space-y-10">
          {/* Section 1 */}
          <div>
            <h2 className="text-xl md:text-2xl font-bold text-gray-800 mb-2">
              Step 4 : Write your Statement of Purpose
            </h2>
            <p className="text-sm text-gray-600 mb-6">
              Tell us about your goals, what you've achieved so far, and why you're a great fit for this scholarship.
            </p>

            <h3 className="text-md md:text-lg font-semibold text-gray-800 mb-2">
              Section 1 : Write your statement of purpose below <span className="text-gray-500 text-sm">(minimum of 200 words)</span>
            </h3>

            <textarea
              value={sop}
              onChange={(e) => setSop(e.target.value)}
              className="w-full h-64 p-4 border-2 border-blue-400 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-800"
              placeholder="I am applying for the Ghana STEM Excellence Scholarship because I am passionate about using technology to solve real-world problems..."
            ></textarea>

            <div className="flex justify-between items-center mt-4 text-sm text-gray-600">
              <div className="space-x-3">
                <button className="bg-blue-600 hover:bg-blue-700 text-white py-1 px-4 rounded">Preview</button>
                <button className="font-bold">B</button>
                <button className="italic">I</button>
                <button className="underline">U</button>
                <button className="">Aa</button>
              </div>
              <div>
                Word count: {wordCount} / 1,500 words
              </div>
            </div>
          </div>

          {/* Section 2 */}
          <div className="bg-gray-50 p-6 rounded-2xl border border-gray-200">
            <h3 className="text-md md:text-lg font-semibold text-gray-800 mb-4">
              Section 2 : Capstone AI Assistant
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              Let our Capstone AI assistant draft a personalised version for you using your earlier uploaded documents.
            </p>

            <label htmlFor="highlight" className="block text-sm font-medium text-gray-700 mb-1">
              Tell us what you want your statement of purpose to highlight
            </label>
            <div className="flex items-center space-x-2">
              <input
                type="text"
                id="highlight"
                value={highlight}
                onChange={(e) => setHighlight(e.target.value)}
                className="flex-1 p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder='e.g. "Please focus on my academic challenges and my goal to work in AI ethics."'
              />
              <button className="bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded">
                Generate with AI
              </button>
            </div>

            <p className="text-xs text-blue-700 mt-4">
              <strong>Please note:</strong> Any statement generated by Capstone AI will be clearly labelled and added below your original writing – your original text won’t be lost. Capstone AI only uses the documents you’ve uploaded to create helpful suggestions that reflect your story.
            </p>
          </div>
        </div>

        {/* Action Buttons and Note */}
        <div className="w-full lg:w-64 flex flex-col gap-4">
          <button className="px-5 py-2 bg-blue-500 text-white rounded-md w-full">
            Save Progress
          </button>
          <button className="px-5 py-2 bg-gray-200 text-black rounded-md w-full">
            Back to Homepage
          </button>
          <p className="text-red-500 text-xs text-center mt-2">
            Note: Applications close on 26th March 2025
          </p>
        </div>
      </div>
    </div>
  );
}
